version: 2

run:
  go: "1.24"
  timeout: 10m

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - bodyclose
    - contextcheck
    - cyclop
    - dupl
    - durationcheck
    - gosec
    - misspell
    - revive

linters-settings:
  revive:
    rules:
      - name: exported

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gosec
        - errcheck
