version: "2"

run:
  go: "1.24"
  timeout: 10m

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - bodyclose
    - contextcheck
    - cyclop
    - dupl
    - durationcheck
    - gosec
    - misspell
    - revive

  settings:
    revive:
      rules:
        - name: exported

  exclusions:
    rules:
      - path: _test\.go
        linters:
          - gosec
          - errcheck
