name: Security

on:
  push:
    branches: [master, develop]
  pull_request:
    branches: [master, develop]

jobs:
  security:
    name: Security Scan
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.23"

      - name: Cache Go modules
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Fix dependencies
        run: ./.github/scripts/fix-deps.sh

      - name: Run Gosec Security Scanner
        run: |
          bash -c "go install github.com/securego/gosec/v2/cmd/gosec@latest"
          gosec -fmt sarif -out gosec.sarif ./... || true

      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: gosec.sarif
        if: always() && hashFiles('gosec.sarif') != ''
